import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import ExcelJS from 'exceljs';
import { importSpreadsheet, exportSpreadsheet } from '../src/workspaceSpreadsheet.ts';
const book = new ExcelJS.Workbook();
const first = book.addWorksheet('需求');
first.getCell('A1').value = '中文\n多行';
first.getCell('A1').font = { bold: true, color: { argb: 'FF123456' } };
first.getCell('A1').alignment = { wrapText: true };
first.getCell('B2').value = 12.5;
first.getCell('B2').numFmt = '0.00';
first.getCell('C2').value = { formula: 'B2*2', result: 25 };
first.getCell('A3').value = true;
first.getCell('B3').value = new Date('2026-09-16T00:00:00Z');
first.mergeCells('A5:C6'); first.getCell('A5').value = '合并';
first.getRow(5).height = 32; first.getColumn(1).width = 24;
book.addWorksheet('第二页').getCell('A1').value = '保留';
const encoded = Buffer.from(await book.xlsx.writeBuffer()).toString('base64');
const data = await importSpreadsheet(encoded, 'test.xlsx');
assert.equal(data.sheetOrder.length, 2);
const sheet = data.sheets[data.sheetOrder[0]];
assert.equal(sheet.cellData[1][2].f, '=B2*2');
assert.equal(sheet.cellData[0][0].s.bl, 1);
sheet.cellData[0][0].v = '修改后';
sheet.cellData[1][1].v = 30;
sheet.cellData[2][0] = { v: null };
sheet.cellData[7] = { 0: { v: '新增' } };
const saved = await exportSpreadsheet(data);
const reopened = new ExcelJS.Workbook();
await reopened.xlsx.load(Buffer.from(saved, 'base64'));
const ws = reopened.getWorksheet('需求');
assert.equal(ws.getCell('A1').value, '修改后');
assert.equal(ws.getCell('A1').font.bold, true);
assert.equal(ws.getCell('B2').value, 30);
assert.equal(ws.getCell('B2').numFmt, '0.00');
assert.equal(ws.getCell('C2').formula, 'B2*2');
assert.equal(ws.getCell('A3').value, null);
assert.equal(ws.getCell('B3').value.toISOString(), '2026-09-16T00:00:00.000Z');
assert.equal(ws.getCell('A8').value, '新增');
assert.deepEqual(ws.model.merges, ['A5:C6']);
assert.equal(ws.getRow(5).height, 32);
assert.equal(ws.getColumn(1).width, 24);
assert.equal(reopened.getWorksheet('第二页').getCell('A1').value, '保留');
await assert.rejects(() => importSpreadsheet('AAAA', 'broken.xlsx'));
// A tiny file can apply validation to every Excel cell. Keep this regression bounded
// even if the importer accidentally resumes expanding those ranges in the future.
const validationBook = new ExcelJS.Workbook();
const validationSheet = validationBook.addWorksheet('整列校验');
validationSheet.getCell('A1').value = '保留内容';
validationSheet.getCell('B2').value = { formula: '1+1', result: 2 };
validationSheet.dataValidations.add('A2:XFD1048576', { type: 'list', formulae: ['"是,否"'] });
const validationFile = Buffer.from(await validationBook.xlsx.writeBuffer()).toString('base64');
const regression = spawnSync(process.execPath, ['--max-old-space-size=128', '--input-type=module', '-e', `
  import { readFileSync } from 'node:fs';
  import { importSpreadsheet } from ${JSON.stringify(new URL('../src/workspaceSpreadsheet.ts', import.meta.url).href)};
  const snapshot = await importSpreadsheet(readFileSync(0, 'utf8'), 'validation.xlsx');
  const sheet = snapshot.sheets[snapshot.sheetOrder[0]];
  console.log(JSON.stringify([sheet.cellData[0][0].v, sheet.cellData[1][1].f, sheet.rowCount, sheet.columnCount]));
`], { input: validationFile, encoding: 'utf8', timeout: 10_000, windowsHide: true });
assert.equal(regression.status, 0, `whole-column validation import failed: ${regression.error ?? regression.stderr}`);
assert.deepEqual(JSON.parse(regression.stdout), ['保留内容', '=1+1', 100, 26]);
console.log('spreadsheet import/edit/export checks passed');
